kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: postgres
  name: postgres-data-volume
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
